### PR TITLE
Force rosinterfacepool to not duplicate interfaces 

### PR DESCRIPTION
**Pull request by NadiaHG**
Includes https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/pull/3 together with https://github.com/ipa320/ros-model/pull/42 should solve all the problems

### CODE REVIEW

**Comment by NadiaHG** [comment]
@alex-lotz please test and review: https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/pull/4/commits/4702a49920c65f1b6fda40a8bb04e85a11bcef11

**Comment by NadiaHG** [comment]
Example for the test:

```
ComponentInterface { name robotino
RosPublishers{
	RosPublisher "joy" { RefPublisher "joy.joy_node.joy_node.joy"},
	RosPublisher "diagnostics" { RefPublisher "joy.joy_node.joy_node.diagnostics"},
	RosPublisher "joint_states" { RefPublisher "robotino_driver.robotino_driver.robotino_driver.joint_states"},
	RosPublisher "bumper" { RefPublisher "robotino_driver.robotino_driver.robotino_driver.bumper"},
	RosPublisher "sondar_scan" { RefPublisher "robotino_driver.robotino_driver.robotino_driver.sondar_scan"},
	RosPublisher "tf" { RefPublisher "robot_state_publisher.robot_state_publisher_node.robot_state_publisher.tf"},
	RosPublisher "cmd_vel" { RefPublisher "robotino_teleop.joystick_teleop_node.joystick_teleop_node.cmd_vel"},
	RosPublisher "odom" { RefPublisher "robotino_driver.robotino_odometry_node.robotino_odometry_node.odom"},
	RosPublisher "scan" { RefPublisher "hokuyo_node.hokuyo_node.hokuyo_node.scan"},
	RosPublisher "hokuyo/parameter_descriptions" { RefPublisher "hokuyo_node.hokuyo_node.hokuyo_node.hokuyo/parameter_descriptions"},
	RosPublisher "hokuyo/parameter_updates" { RefPublisher "hokuyo_node.hokuyo_node.hokuyo_node.hokuyo/parameter_updates"}
	}
RosSubscribers{
	RosSubscriber "cmd_vel" { RefSubscriber "robotino_driver.robotino_driver.robotino_driver.cmd_vel"},
	RosSubscriber "joint_states" { RefSubscriber "robot_state_publisher.robot_state_publisher_node.robot_state_publisher.joint_states"},
	RosSubscriber "joy" { RefSubscriber "robotino_teleop.joystick_teleop_node.joystick_teleop_node.joy"}
	}
RosSrvClients{
	RosServiceClient "reset_odometry" { RefClient "robotino_driver.robotino_odometry_node.robotino_odometry_node.reset_odometry"},
	RosServiceClient "hokuyo/set_parameters" { RefClient "hokuyo_node.hokuyo_node.hokuyo_node.hokuyo/set_parameters"},
	RosServiceClient "hokuyo/self_test" { RefClient "hokuyo_node.hokuyo_node.hokuyo_node.hokuyo/self_test"}
	}
}
```

save file as  _robotino.componentinterface_  and by right click button "Generate Ros interface pool".

The generated file should look like:
```
RosInterfacesPool {
	RosSubscriber joy_sub { topicName "joy" type "sensor_msgs.Joy" }
	RosSubscriber diagnostics_sub { topicName "diagnostics" type "diagnostic_msgs.DiagnosticArray" }
	RosSubscriber joint_states_sub { topicName "joint_states" type "sensor_msgs.JointState" }
	RosSubscriber bumper_sub { topicName "bumper" type "std_msgs.Bool" }
	RosSubscriber sondar_scan_sub { topicName "sondar_scan" type "sensor_msgs.LaserScan" }
	RosSubscriber tf_sub { topicName "tf" type "tf2_msgs.TFMessage" }
	RosSubscriber cmd_vel_sub { topicName "cmd_vel" type "geometry_msgs.Twist" }
	RosSubscriber odom_sub { topicName "odom" type "nav_msgs.Odometry" }
	RosSubscriber scan_sub { topicName "scan" type "sensor_msgs.LaserScan" }
	RosSubscriber hokuyo_parameter_descriptions_sub { topicName "hokuyo/parameter_descriptions" type "dynamic_reconfigure.ConfigDescription" }
	RosSubscriber hokuyo_parameter_updates_sub { topicName "hokuyo/parameter_updates" type "dynamic_reconfigure.Config" }
	RosPublisher cmd_vel_pub { topicName "cmd_vel" type "geometry_msgs.Twist" }
	RosPublisher joint_states_pub { topicName "joint_states" type "sensor_msgs.JointState" }
	RosPublisher joy_pub { topicName "joy" type "sensor_msgs.Joy" }
	RosSrvClient reset_odometry_srvcli { srvName "reset_odometry" type "robotino_msgs.ResetOdometry" }
	RosSrvClient hokuyo_set_parameters_srvcli { srvName "hokuyo/set_parameters" type "dynamic_reconfigure.Reconfigure" }
	RosSrvClient hokuyo_self_test_srvcli { srvName "hokuyo/self_test" type "diagnostic_msgs.SelfTest" }
}

```

**Review by alex-lotz — CHANGES_REQUESTED** [review]
It seems that you are not filtering duplicates after all. I think this is not optional, because you typically translate e.g. RosSubscribers (from ROS tooling) to RosPublishers in the RosInterfacesPool model and i believe that the duplicates will appear very likely. I suggest that you actively filter out duplicates which should be straight forward and a small refinement.

**Comment by NadiaHG** [comment]
The ComponentInterface is filtering them https://github.com/ipa320/ros-model/pull/42/files

**Comment by alex-lotz** [comment]
> The ComponentInterface is filtering them https://github.com/ipa320/ros-model/pull/42/files

Now I am lost, do you filter the items in the original ROS tooling manually, because before we had a different example of a real ros system that seemed to be realistic, now we have a potentially simplified example that (fortunately) circumvents the problem?

**Comment by NadiaHG** [comment]
I am not doing any step manually the original and real system is the same https://github.com/ipa320/ros-model/blob/master/examples/robotino_example/robotino.rossystem 

The componentInterface is **autogenerated**, the one I had before was wrong because I had duplicated interfaces and conceptually was wrong, with the code modification https://github.com/ipa320/ros-model/pull/42/files this can't happen anymore. The rosinterfacepool is basically a copy of the componentinterfaces but removing references and it is also **autogenarated**, I don't want to add here any intelligence for this model because it is a totally fictitious model without a real conceptual meaning

**Comment by alex-lotz** [comment]
> The rosinterfacepool is basically a copy of the componentinterfaces but removing references and it is also **autogenarated**, I don't want to add here any intelligence for this model because it is a totally fictitious model without a real conceptual meaning

I quite disagree here, and I could say the very same statement towards the Componentnterface model (which now became even less reasonable), but lets stop this pointless discussion here. Since, the end result "on my side" is the same, we can use this approach.

**Review by alex-lotz — APPROVED** [review]

**Comment by NadiaHG** [comment]
The ComponentInterface is part of the ROS model, and it is totally necessary otherwise I can't define ROS systems from ROS code. This model is **not only** used for the gateway.

**Pull request merged**
