### PR TITLE
Add support for maven builds and consequently travis CI builds

### PR DESCRIPTION
**Pull request by NadiaHG**
@alex-lotz this PR ensure the quality and stability of the software by testing every PR or change made on the software. Travis (travis-ci.org) will trigger automatically a new build and let us now if we pass the tests (for now just compile through dependencies versions) , for example https://travis-ci.org/ipa-nhg/SeRoNet-Tooling-ROS-Mixed-Port/builds/563052248?utm_source=github_status&utm_medium=notification 

This is very useful for the review process and also gives us credit in terms of professional code development

For now I just made an example to the projects related to the ros-model (as for the ROS tooling I have already fully integrated all the tests) I will continue with the dependencies to your models, I will have to work on my branch and I will open a PR to your upstream repository, let me know if you are interested on extend the support to your projects (strongly recommended) or keep a separate branch for the changes.

### CODE REVIEW

**Comment by alex-lotz** [comment]
I am fully aware of travis CI and I already have investigated this option in the past. travis CI requires a headless build of the entire Eclipse codebase using e.g. Maven/Tycho build. For simple hello world examples, this works fine. However, for our current toolchain this would mean to change the current build process entirely which is a lot of work which we will not do within SeRoNet anymore (but maybe in some future projects). To answer your question, no CI build for our stuff for now.

**Comment by NadiaHG** [comment]
Ok, my plan is actually test the grammar (and obviously the metamodels) to be sure that we don't break anything by developing the `parent` models in parallel. A test similar to this one: https://github.com/ipa320/ros-model/blob/master/plugins/de.fraunhofer.ipa.ros.xtext.tests/src/de/fraunhofer/ipa/ros/tests/RosParsingTest.xtend#L21-L55 by parsing an example.

I have already a working version to test the ros.interface.pool model, based on this pom.xml file https://github.com/ipa-nhg/SeRoNet-Tooling-ROS-Mixed-Port/blob/travis2/SeRoNet-Tooling-ROS-Mixed-Port.parent/pom.xml#L20-L34 , this should be enough for the test I want to implement.

The only package that I am not building of this repo is the `de.seronet_projekt.xtend.ROS.generator` as it has dependencies to many of your projects. I have started  adding pom files to the SmartMDSD-Toolchain projects but if you don't want to support it with your own tests I think make not much sense that I spend more time.

**Comment by alex-lotz** [comment]
That is my point, creating a pom for a top-level (single) project is kindergarden (its like half an hour of work). But if you start building all the plugins with all their dependencies, then, believe me or not, but you will spend the next couple of months (maybe half a year) just doing that and nothing else. But if you want doing that, I won't stop you, in fact I am even interested in reviewing the result. :-)

**Review by mathias-luedtke — APPROVED** [review]

**Comment by NadiaHG** [comment]
@alex-lotz 
I though also, because of the available documentation, that it was super hard but it isn't. We have already it integrate for all our projects and it took for us a couple of days (starting from scratch) , now that we have examples of pom files for EMF, Xtext and Xtend projects is "just" a copy-paste of templates forms and modify the name of the artifacts. I started yesterday with some of your projects https://github.com/ipa-nhg/SmartMDSD-Toolchain/commit/211b1430cca87105498adbb917ffbefbd8cae31f but I stop when I saw your [comment](https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/pull/12#issuecomment-514668161),  if you will not merge it to your main branch and allow Travis to support it make not sense to continue.

Have a system that automatically builds each PR or change is a great benefit as it reduces considerably the review and debug efforts. Also Travis can be configured to automatically build and generate releases of software.
But again, this is up to you, it is your software.

**Comment by NadiaHG** [comment]
Supersede by https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/pull/13

**Comment by NadiaHG** [comment]
superseded by https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/pull/33 and https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/pull/34
--> close

**Pull request closed without merging**
