### PR TITLE
Fix ros mixed port ros code generator

### PR DESCRIPTION
**Pull request by NadiaHG**

### CODE REVIEW

**Comment by alex-lotz** [comment]
@ipa-nhg Can you at least provide a bit more context, what is the bug, what does not work and what is your fix fixing or not?

**Comment by NadiaHG** [comment]
`hasRosPorts` was always false, that means the ros code was not being generated.

The problem was this line https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/blob/master/de.seronet_projekt.xtend.ROS.generator/src/de/seronet_projekt/xtend/ROS/generator/ROSGenerator.java#L65, you have to look for the component in the content of the object.

**Review by alex-lotz — CHANGES_REQUESTED** [review]
Ok, now it is a bit more clear. Your are "half correct". It seems there is indeed a mistake that slipped through my tests. However, the proposed solution is not quite correct. Actually, the obj should be tested for "ComponentDefModel" instead of the "ComponentDefinition" which is a sub-element of the former. So you like to fix it?

**Comment by NadiaHG** [comment]
I already tried that and didn't work, I got an error because the object couldn't be cast as `ComponentDefModel` , here: https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/blob/master/de.seronet_projekt.xtend.ROS.generator/src/de/seronet_projekt/xtend/ROS/generator/ROSGenerator.java#L66 

But can be I did something wrong, this is related to the smartsoft component model and I am not that expert with your models..

**Comment by alex-lotz** [comment]
Ok, then I am going to fix it myself.

**Pull request closed without merging**
