### PR TITLE
M2M for SeRoNet-ROS communication objects with examples

### PR DESCRIPTION
**Pull request by NadiaHG**
Related to https://github.com/seronet-project/seronet-intern/issues/37

The main idea is transform automatically ROS msgs **and srvs** to SeRoNet communication types **and services**, this can simplify and improve  significantly the code generation.

~~A first prototype is implemented and successfully tested for simple cases. For example from: https://github.com/ipa-nhg/SeRoNet-Tooling-ROS-Mixed-Port/blob/239efee55479d00f2b9ea3c9920db21d5504ce95/de.seronet_projekt.ros.componentGateway.generator/example/geometry_msgs.ros to https://github.com/ipa-nhg/SeRoNet-Tooling-ROS-Mixed-Port/blob/239efee55479d00f2b9ea3c9920db21d5504ce95/de.seronet_projekt.ros.componentGateway.generator/example/geometry_msgs.types~~

UPDATE:

From 
https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/blob/dd348b4c88ab18c5732c46747b0cf681795adcc8/de.seronet_projekt.ros.componentGateway.generator/example/ros_core.ros

We can generate automatically:
https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/blob/dd348b4c88ab18c5732c46747b0cf681795adcc8/de.seronet_projekt.ros.componentGateway.generator/example/std_msgs.types
https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/blob/dd348b4c88ab18c5732c46747b0cf681795adcc8/de.seronet_projekt.ros.componentGateway.generator/example/std_srvs.types
https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/blob/dd348b4c88ab18c5732c46747b0cf681795adcc8/de.seronet_projekt.ros.componentGateway.generator/example/ros_core.services

I tested on with the latest Smartsoft release and it is working, that means the grammar is right and all the header files for the communication object types auto generated

### CODE REVIEW

**Comment by NadiaHG** [comment]
@alex-lotz I am still missing the Enumerations like https://github.com/Servicerobotics-Ulm/DomainModelsRepositories/blob/master/CommBasicObjects/model/CommBasicObjects.types#L116-L120

could you please help me to understand the use of this model definition? could you please give me an example ?

Thanks!

**Comment by alex-lotz** [comment]
Enums are often used with Events where you very often have a predefined set of discrete values, like GOAL_REACHED, PATH_OCCUPIED, etc. For that we don't encode it as string but use a more efficient enum which is just an int underneath.

Right now I don't have time to make reviews or provide more elaborate explanations as I am working on a different topic. But from what you described in this PR, this sounds ok to me.

**Comment by NadiaHG** [comment]
For me this is ready to be merged. The last commits are related to:

* updated the names to follow the SmartSoft conventions (like capitalize the name of the repository and the name of the object).
* use the Smartsoft definition of time by default (the information is the same for both frameworks)
* implemented the enumerations. The ROS and SmartSoft concepts are a bit different but at least with this approach we automatize successfully the translation.

I did several tests and this is always working, that means the generated model follows the CommunicationObject xtext grammar (no errors, no warnings), the code is generated (smartsoft folder) and its compiles.

**Review by alex-lotz — CHANGES_REQUESTED** [review]
Most of it looks fine, the only thing I noticed is that a "byte" type from ROS could be translated to a "UInt8" in SmartSoft (because this is the typical representation of a byte in most systems anyways). The rest looks fine.

**Comment by NadiaHG** [comment]
Actually the type byte is deprecated, but some old messages still includes it. However ROS interpret it as a int8 (but I have never seen a signed byte...)

```
Deprecated:
    char: deprecated alias for uint8
    byte: deprecated alias for int8 
```
(http://wiki.ros.org/msg#Field_Types)

**Comment by alex-lotz** [comment]
> Actually the type byte is deprecated, but some old messages still includes it. However ROS interpret it as a int8 (but I have never seen a signed byte...)
> 
> ```
> Deprecated:
>     char: deprecated alias for uint8
>     byte: deprecated alias for int8 
> ```
> 
> (http://wiki.ros.org/msg#Field_Types)

Ok I see. In the end, it does not make much difference if a byte is either translated to an int8 or an uint8 (they have the same size). However, some newer compilers will probably complain with an error that these types are incompatible (although they are not so different after all).  I think it still is better to translate a byte into some type instead of not translating it at all and leave the atttribute empty. You could even generate a comment that "the attribute has been generated from a deprecated  byte type" (or something similar).

Overall, I know the problem of dealing with legacy and deprecated features. There is no perfect solution, but since there is probably a lot of software available that still uses such deprecated types, the only viable solution is just to continue supporting them for some time until all relevant software moves to the newer types.

**Comment by NadiaHG** [comment]
Ok, I will add a comment to notify the byte->uint8 tranformation

**Comment by alex-lotz** [comment]
@ipa-nhg The last commit looks fine to me. How can I change my review to "approved"?

**Review by alex-lotz — APPROVED** [review]

**Comment by NadiaHG** [comment]
Thanks for the review!

**Pull request merged**
