### PR TITLE
Feature/refined mixedport

### PR DESCRIPTION
**Pull request by alex-lotz**
- Refined ROS MixedPort component realization using the new, generic and extensible MixedPort Base Metamodel
- Added graphical modeling support for ROS MixedPort
- Extended ROS C++ code generator that now also supports ActionLib
- Updated ROS Joystick example using the new modeling capabilities

### CODE REVIEW

**Comment by NadiaHG** [comment]
Blocked by https://github.com/seronet-project/SeRoNet-Tooling-Infrastructure/issues/27

**Comment by NadiaHG** [comment]
image
 depends on https://github.com/Servicerobotics-Ulm/SmartMDSD-Toolchain/tree/feature/refined-mixedport ????

**Review by NadiaHG — CHANGES_REQUESTED** [review]
I get the following error when I open the  `ComponentRosJoystick.component` file:

> Failed to create injector for org.xtext.component.componentDefinition.ComponentDefinition (occurred in org.xtext.component.componentDefinition.ui.ComponentDefinitionExecutableExtensionFactory)

**Comment by alex-lotz** [comment]
> image
> depends on https://github.com/Servicerobotics-Ulm/SmartMDSD-Toolchain/tree/feature/refined-mixedport ????

Do you still have this error? It is probably because you missed to import one of the new plugins related to mixed-port.

**Comment by alex-lotz** [comment]
> I get the following error when I open the `ComponentRosJoystick.component` file:
> 
> > Failed to create injector for org.xtext.component.componentDefinition.ComponentDefinition (occurred in org.xtext.component.componentDefinition.ui.ComponentDefinitionExecutableExtensionFactory)

Not sure what this might be, can you give a bit more context. Is it an exception, do you have a stack-trace?

**Comment by NadiaHG** [comment]
> > image
> > depends on https://github.com/Servicerobotics-Ulm/SmartMDSD-Toolchain/tree/feature/refined-mixedport ????
> 
> Do you still have this error? It is probably because you missed to import one of the new plugins related to mixed-port.

Yes I solved this using the branch "feature/refined/mixedport", please remember to mention the needed version to test PRs if requires some changed not included in a default branch for a repo or release version.

**Comment by NadiaHG** [comment]
Following the instructions https://github.com/seronet-project/SeRoNet-Tooling-Infrastructure/issues/27#issuecomment-493880198 I got:

`Caused by: org.eclipse.xtext.resource.ClasspathUriResolutionException: org.eclipse.xtext.resource.FileNotFoundOnClasspathException: Couldn't find resource on classpath. URI was 'classpath:/org/xtext/component/componentParameter/ComponentParameter.xmi'
`



`
[Worker-3: Updating project 'ComponentRosJoystick'] ERROR org.eclipse.xtext.resource.impl.ResourceServiceProviderRegistryImpl  - Erroneous resource service provider registered for 'platform:/resource/ComponentRosJoystick/model/ComponentRosJoystick.componentParameters'. Removing it from the registry.
java.lang.ClassCastException: The type null is not a valid interface org.eclipse.xtext.resource.IResourceServiceProvider or interface 
`

**Comment by NadiaHG** [comment]
Ok, I had to re-generate all SmartMDSD-Toolchain Xtext Artifacts... @alex-lotz  do you know how can be solved this issue? 

The joy example is working as expected, this version looks really good! :smile: 

I still have an issue when I try with a more complex ROS model, for example the robotino one (https://github.com/ipa320/ros-model/blob/master/examples/robotino_example/robotino.rossystem) that correspond to the following rosinterfacespool model:

```
RosInterfacesPool {
	RosSubscriber joy { topicName "joy" type "sensor_msgs.Joy" }
	RosSubscriber diagnostics { topicName "diagnostics" type "diagnostic_msgs.DiagnosticArray" }
	RosSubscriber joint_states { topicName "joint_states" type "sensor_msgs.JointState" }
	RosSubscriber bumper { topicName "bumper" type "std_msgs.Bool" }
	RosSubscriber sondar_scan { topicName "sondar_scan" type "sensor_msgs.LaserScan" }
	RosSubscriber tf { topicName "tf" type "tf2_msgs.TFMessage" }
	RosSubscriber cmd_vel { topicName "cmd_vel" type "geometry_msgs.Twist" }
	RosSubscriber odom { topicName "odom" type "nav_msgs.Odometry" }
	RosSubscriber tf { topicName "tf" type "tf2_msgs.TFMessage" }
	RosSubscriber scan { topicName "scan" type "sensor_msgs.LaserScan" }
	RosSubscriber diagnostics { topicName "diagnostics" type "diagnostic_msgs.DiagnosticArray" }
	RosSubscriber hokuyo_parameter_descriptions { topicName "hokuyo/parameter_descriptions" type "dynamic_reconfigure.ConfigDescription" }
	RosSubscriber hokuyo_parameter_updates { topicName "hokuyo/parameter_updates" type "dynamic_reconfigure.Config" }
	RosPublisher cmd_vel { topicName "cmd_vel" type "geometry_msgs.Twist" }
	RosPublisher joint_states { topicName "joint_states" type "sensor_msgs.JointState" }
	RosPublisher joy { topicName "joy" type "sensor_msgs.Joy" }
	RosSrvClient reset_odometry { srvName "reset_odometry" type "robotino_msgs.ResetOdometry" }
	RosSrvClient hokuyo_set_parameters { srvName "hokuyo/set_parameters" type "dynamic_reconfigure.Reconfigure" }
	RosSrvClient hokuyo_self_test { srvName "hokuyo/self_test" type "diagnostic_msgs.SelfTest" }
}
```

I got errors for the interfaces `joy`, `diagnostics`, `joint_states`, `tf`, `cmd_vel` and `odom` all of them  are marked as duplicated and this is totally right and quite common (find on a system a publisher and a subscriber for a topic), @alex-lotz how to solve this? rewrite the ecore model again or change the Xtext grammar to allow this?

**Comment by alex-lotz** [comment]
> Ok, I had to re-generate all SmartMDSD-Toolchain Xtext Artifacts... @alex-lotz do you know how can be solved this issue?
> 
> The joy example is working as expected, this version looks really good! 
> 
> I still have an issue when I try with a more complex ROS model, for example the robotino one (https://github.com/ipa320/ros-model/blob/master/examples/robotino_example/robotino.rossystem) that correspond to the following rosinterfacespool model:
> 
> ```
> RosInterfacesPool {
> 	RosSubscriber joy { topicName "joy" type "sensor_msgs.Joy" }
> 	RosSubscriber diagnostics { topicName "diagnostics" type "diagnostic_msgs.DiagnosticArray" }
> 	RosSubscriber joint_states { topicName "joint_states" type "sensor_msgs.JointState" }
> 	RosSubscriber bumper { topicName "bumper" type "std_msgs.Bool" }
> 	RosSubscriber sondar_scan { topicName "sondar_scan" type "sensor_msgs.LaserScan" }
> 	RosSubscriber tf { topicName "tf" type "tf2_msgs.TFMessage" }
> 	RosSubscriber cmd_vel { topicName "cmd_vel" type "geometry_msgs.Twist" }
> 	RosSubscriber odom { topicName "odom" type "nav_msgs.Odometry" }
> 	RosSubscriber tf { topicName "tf" type "tf2_msgs.TFMessage" }
> 	RosSubscriber scan { topicName "scan" type "sensor_msgs.LaserScan" }
> 	RosSubscriber diagnostics { topicName "diagnostics" type "diagnostic_msgs.DiagnosticArray" }
> 	RosSubscriber hokuyo_parameter_descriptions { topicName "hokuyo/parameter_descriptions" type "dynamic_reconfigure.ConfigDescription" }
> 	RosSubscriber hokuyo_parameter_updates { topicName "hokuyo/parameter_updates" type "dynamic_reconfigure.Config" }
> 	RosPublisher cmd_vel { topicName "cmd_vel" type "geometry_msgs.Twist" }
> 	RosPublisher joint_states { topicName "joint_states" type "sensor_msgs.JointState" }
> 	RosPublisher joy { topicName "joy" type "sensor_msgs.Joy" }
> 	RosSrvClient reset_odometry { srvName "reset_odometry" type "robotino_msgs.ResetOdometry" }
> 	RosSrvClient hokuyo_set_parameters { srvName "hokuyo/set_parameters" type "dynamic_reconfigure.Reconfigure" }
> 	RosSrvClient hokuyo_self_test { srvName "hokuyo/self_test" type "diagnostic_msgs.SelfTest" }
> }
> ```
> 
> I got errors for the interfaces `joy`, `diagnostics`, `joint_states`, `tf`, `cmd_vel` and `odom` all of them are marked as duplicated and this is totally right and quite common (find on a system a publisher and a subscriber for a topic), @alex-lotz how to solve this? rewrite the ecore model again or change the Xtext grammar to allow this?

I am glad that it works on your side as well now.

Regarding the naming conflicts, although it would be quite simple to deactivate the duplicate check within the RosInterfacesPool Xtext grammar, it would only shift the problem to the later steps. First, the component model would also yield duplicates, and second, even worse, the generated code will also not compile as the generated variable names would conflict as well. So in conclusion, the only really robust solution is to somehow generate unique names. I am not sure what is the best approach here, though. Is there maybe a kind of Node name in your DSL, which could be used to construct the interface name with a prefix?

**Comment by alex-lotz** [comment]
@ipa-nhg I just had a closer look into the robotino.rossystem example and there is the ComponentInterface name that can be used either as a prefix in the RosInterface name, something like this:

```
<ComponentInterfaceName>_<RosPortName>
```
This seems to be a really simple solution with minimal changes, as only the RosInterfacesPool generator would need to be slightly refined without affecting anything else.

**Comment by mathias-luedtke** [comment]
From @alex-lotz:
> <ComponentInterfaceName>_<RosPortName>

What is `ComponentInterfaceName` is this context?

From @ipa-nhg:
> I got errors for the interfaces joy, diagnostics, joint_states, tf, cmd_vel and odom all of them are marked as duplicated and this is totally right and quite common (find on a system a publisher and a subscriber for a topic)

There are duplicated publishers, which is wrong at this level.

**Comment by alex-lotz** [comment]
@ipa-nhg Btw. would it make sense to exchange the current very simple joystick example for something more realistic around your shown robotino example?

**Comment by alex-lotz** [comment]
> What is `ComponentInterfaceName` is this context?
> 

See example: https://github.com/ipa320/ros-model/blob/master/examples/robotino_example/robotino.rossystem

Don't blame me for the "ComponentInterface" element name, I would probably name it differently. :-)

**Comment by mathias-luedtke** [comment]
> See example: https://github.com/ipa320/ros-model/blob/master/examples/robotino_example/robotino.rossystem

I see. No, we can't use this, it would break the semantics.
I could imaging to prefix it with the interface type.
(This is what ROS2 does.)

> Don't blame me for the "ComponentInterface" element name, I would probably name it differently. :-)

Just fight with OMG about it ;)

**Comment by NadiaHG** [comment]
@alex-lotz I don't think we should use the name of the node and much less the name of the ComponentInterface , we are then mixing things and concepts. At this level (the gateway) we are just interested on the name of the interface, its nature and the communication object, the intention here was to list all the interfaces offered by a ROS master.

I will go for a prefix that indicates the type of the interface, for example: joy_pub

**Comment by alex-lotz** [comment]
> @alex-lotz I don't think we should use the name of the node and much less the name of the ComponentInterface , we are then mixing things and concepts. At this level (the gateway) we are just interested on the name of the interface, its nature and the communication object, the intention here was to list all the interfaces offered by a ROS master.
> 
> I will go for a prefix that indicates the type of the interface, for example: joy_pub

I think this might not be enough in general. For publishers this might help (provided there is one publisher per interface), but if you have several subscribers for the same topic (which is definitely reasonable), then the problem will be the same.

Another option, or maybe a question to @ipa-nhg and @ipa-mdl. If the topics with the same name are (in particular the subscriber side) are really equal (regarding the interface specification), then one could also filter out the duplicates prior to "dumping" (i.e. while generating) the RosInterfacesPool model. In the end, duplicates for the same topic make no much sense anyways. What do you think? I feel this might be the best solution without changing the semantics.

**Comment by NadiaHG** [comment]
> I think this might not be enough in general. For publishers this might help (provided there is one publisher per interface), but if you have several subscribers for the same topic (which is definitely reasonable), then the problem will be the same.

For the level that we are considering (i.e. the bridge) this is general enough you don't care if you have several subscriber for one topic, if you publish something all the subscribers will get the message you only need to know the name of the topic and the message type (that is the same for all) and the roscore will manage the communication with all the subscribers.

All issues are solved by:
https://github.com/seronet-project/SeRoNet-Tooling-ROS-Mixed-Port/pull/4
https://github.com/ipa320/ros-model/pull/42

@alex-lotz Please test

**Pull request merged**
